apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer-bk
  namespace: ziohexa
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert-bk
  namespace: ziohexa
spec:
  secretName: selfsigned-cert-tls-bk
  commonName: bookkeeper-webhook-svc.ziohexa.svc.cluster.local
  dnsNames:
    - bookkeeper-webhook-svc
    - bookkeeper-webhook-svc.ziohexa.svc.cluster.local
    - bookkeeper-webhook-svc.ziohexa.svc
  issuerRef:
    name: selfsigned-issuer-bk
