apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer-pv
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert-pv
  namespace: default
spec:
  secretName: selfsigned-cert-tls-pv
  commonName: pravega-webhook-svc.default.svc.cluster.local
  dnsNames:
    - pravega-webhook-svc 
    - pravega-webhook-svc.default.svc.cluster.local
    - pravega-webhook-svc.default.svc
  issuerRef:
    name: selfsigned-issuer-pv

